# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NaSgzvRCaF7hEQ3u8JOMoab0bCxH2qR6
"""

Trails = [SHEARWATER FLYER TRAIL, SANDY LAKE TRAIL, SANDY LAKE TRAIL, MOSS CRT TO MAINLAND LINE]
Trail ID = [3701, 2536, 973, 1489]
Condition = [GOOD, MARGINAL, POOR]

i = 0;
if Trail ID > 3000:
  i+=1;
  print i;

if Condition == Good:
  print ('Active')